### ISSUE TITLE
Bubbles don't appear on multiplayer servers

### ISSUE THREAD

**Issue by SecretlyJealous** [Globox1997/TalkBubbles#2]
Hi, I'm playing on my friends server but the chat bubbles don't appear when a custom chat plugin is used:
![2021-12-09_12 38 49](https://user-images.githubusercontent.com/10485646/145398260-d49f7259-7ec8-4888-941f-3694b94e297a.png)

When my friend removed his chat plugin the chat bubbles worked:
![2021-12-09_12 36 49](https://user-images.githubusercontent.com/10485646/145398347-9dcd5a12-11d8-4a26-b39d-df45078f46a5.png)

I'm also having this problem on a lot of multiplayer servers that are using custom chat plugins, it causes the talkbubbles to not work. Is there a way to fix this?

**Comment by theDerxu** [comment]
same, Wont work on Hypixel either

**Comment by AdolfRoxler** [comment]
yea it no work pls fix how come chatheads work but not this!!!

**Comment by Globox1997** [comment]
Might get fixed with mc version 1.19 since it updates the chat a little bit

**Comment by AnomalousDeity** [comment]
i can also confirm this doesnt work on multiplayer servers in 1.19.2 so far, least from Stoneworks servers i cant see talk bubbles

**Comment by AverageFemale** [comment]
Bump.

**Comment by Globox1997** [comment]
Which chat plugin is used?

**Comment by SecretlyJealous** [comment]
On the server that I play on, they use a custom chat plugin.

**Comment by Globox1997** [comment]
Is it open source? If yes which one

**Comment by SecretlyJealous** [comment]
It's not open source sadly, a lot of the big multiplayer servers such as Hypixel don't have their plugins open source.

**Comment by Globox1997** [comment]
You said your friend has a chat plugin and with that it doesn't work?
If so pls send me his discord

**Comment by yetbad** [comment]
Not work on my server. There are Styled Chat plugin https://modrinth.com/mod/styled-chat that mb a problem

**Comment by Globox1997** [comment]
Uploaded a new version which makes it compatible with styled chat mod

**Comment by AverageFemale** [comment]
I know a lot of server's I'm in use LuckPerms https://github.com/LuckPerms/LuckPerms

**Comment by AverageFemale** [comment]
This and essentials chat
https://github.com/EssentialsX/Essentials/tree/2.x/EssentialsChat

**Comment by MrJorman** [comment]
too problem. I use Styled Chat from the server mod. And Talk Bubbles no working.

**Comment by neila-a** [comment]
> Which chat plugin is used?

Doesn't work on TrChat. (Old version only, of course)
