### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Lualttt** [Globox1997/TalkBubbles#22]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

i have to stand very close to someone to actually read the message, so it would be nice to be able to change the size

or maybe that the size does not change no matter how far away you are from it like the outline thickness of the glowing effect

**Comment by Globox1997** [comment]
Added a config option to the latest version with [https://github.com/Globox1997/TalkBubbles/commit/6a950b779199cc99175d8553995b16fdcac8ee7c](https://github.com/Globox1997/TalkBubbles/commit/6a950b779199cc99175d8553995b16fdcac8ee7c)
