### ISSUE TITLE
Can be marked as 1.20.2 compatible

### ISSUE THREAD

**Issue by sternschnaube** [Globox1997/TalkBubbles#26]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Tested on Fabric with the newest release 😊 
I love this mod.

**Comment by sternschnaube** [comment]
Tested before 1.0.7, tested now 1.0.8 - all works fine. Modrinth version is still listed as only for 1.20.1.

**Comment by Globox1997** [comment]
Marked it as 1.20.2 compatible on modrinth. Thanks for letting me know.

**Comment by sternschnaube** [comment]
Thanks 🥳
