### ISSUE TITLE
TalkBubbles are just black text for me.

### ISSUE THREAD

**Issue by wasiable** [Globox1997/TalkBubbles#28]
### Minecraft Version

1.20.x

### Mod Loader Version

fabric-loader-0.15.9-1.20.4

### Mod Version

v.1.0.8

### Describe the Issue

Hey, 
I am currently playing on the 1.20.4 version of fabric minecraft and my talk bubbles are just black text.
FYI: I'm not using any shaders.
Thanks in advance.

### latest.log

...

**Comment by Globox1997** [comment]
Has to get updated to 1.20.4 I guess

**Comment by wasiable** [comment]
> Has to get updated to 1.20.4 I guess

I actually found the main issue:
The reimagined resource pack seems to remove the "bubble" itself, leaving only the text.
Although the mod version itself being a bit older could cause some problems as well.

Thanks for the reply tho'
