### ISSUE TITLE
[1.19 Fabric] [Bug] [Mod: Artifacts] [Vanilla] The effect of invisibility

### ISSUE THREAD

**Issue by MrJorman** [Globox1997/TalkBubbles#3]
When I am under the effect of invisibility, logically I do not want to see messages on top of me, because I will give out my location. In the Artifacts fashion, there is an invisible scarf, when players write to the chat, an inscription appears above them and they are found. Please make a check of the invisibility effect so that the chat does not appear from above.

**Comment by Globox1997** [comment]
Thanks for reporting this, will fix it when I have time for modding again

**Comment by Globox1997** [comment]
[talkbubbles-1.0.3.zip](https://github.com/Globox1997/TalkBubbles/files/9189660/talkbubbles-1.0.3.zip)
Can you test this pls

**Comment by Globox1997** [comment]
Reopen if still exist with latest version
