### ISSUE TITLE
Suggestion idea

### ISSUE THREAD

**Issue by AnomalousDeity** [Globox1997/TalkBubbles#4]
Allow the talk bubbles appear in single player worlds

**Comment by Globox1997** [comment]
[talkbubbles-1.0.4.zip](https://github.com/Globox1997/TalkBubbles/files/9870316/talkbubbles-1.0.4.zip)
pls test this

**Comment by AnomalousDeity** [comment]
![2022-10-27_11 24 48](https://user-images.githubusercontent.com/91780401/198369258-62fef674-b3ae-4144-abb5-d9d717d7ba56.png)
