### ISSUE TITLE
TalkBubbles not working Version 1.0.3 1.19.2

### ISSUE THREAD

**Issue by MultiBlueGamer** [Globox1997/TalkBubbles#5]
Talk Bubbles isn't working on Servers or single player worlds (Fabric)

**Comment by Globox1997** [comment]
There is no public v1.0.4?

**Comment by MultiBlueGamer** [comment]
sorry I meant 1.0.3

**Comment by Globox1997** [comment]
My guess is, it is the same as [https://github.com/Globox1997/TalkBubbles/issues/2](https://github.com/Globox1997/TalkBubbles/issues/2)

**Comment by MultiBlueGamer** [comment]
Ah yeah is there any fix?

**Comment by Globox1997** [comment]
No but this can be closed than.
Since those plugins are not open source, it is much much harder to figure the issue out.
Basically I need someone who can test stuff on a server
