### ISSUE TITLE
enhanced player detection

### ISSUE THREAD

**Issue by machineonamission** [Globox1997/TalkBubbles#7]
The mod [Chat Heads](https://www.curseforge.com/minecraft/mc-mods/chat-heads) has non-UUID based "heuristics" to detect player heads which works flawlessly even on servers with custom chat plugins. Implementing this could solve #2 .
![image](https://user-images.githubusercontent.com/35177464/215017737-307ba0e7-fff2-424f-a315-f8b1656ce135.png)
Chat Heads is also [open source](https://github.com/dzwdz/chat_heads) though [licensed under a GPL-like](https://github.com/dzwdz/chat_heads/blob/fabric-1.16.x/LICENSE) so I'm not sure you can directly copy the code but you can figure out exactly how this detection works to mimic it

**Comment by Globox1997** [comment]
definitely open for a pull request :)
