### ISSUE TITLE
Please update to 1.19.4

### ISSUE THREAD

**Issue by CCjun6** [Globox1997/TalkBubbles#9]
I like this mod very much but it is not compatible with 1.19.4
Hope you update at your leisure

**Comment by Globox1997** [comment]
Updated with the PR [https://github.com/Globox1997/TalkBubbles/commit/72820991981d61cf9619aab74260a223f09676ea](https://github.com/Globox1997/TalkBubbles/commit/72820991981d61cf9619aab74260a223f09676ea)
